### ISSUE TITLE
what is soft obstacle or soft Soft constraints

### ISSUE THREAD

**Issue by siml142857** [Jiaoyang-Li/MAPF-LNS2#1]
在MAPF-LNS2的论文和代码实现中，提到了soft obstacle和hard obstacle，但是该论文和SIPP论文均没有对这一名词做出定义，所以这个是指的什么？是将agent视为动态障碍物即为soft obstacle吗？hard obstacle是指静止的agent？谢谢解答

**Comment by nobodyczcz** [comment]
将其他agent视为Soft obstacle是指sipps允许生成和其他agent相撞的node，也就是说可以plan有碰撞的path，但是sipps的第一优化目标也被更改为了最小化path上的碰撞的数量。
将其他agent视为Hard obstacle是指不允许生成和其他agent相撞的node， 只plan 无碰撞的path，优化目标也只是path 长度。

**Comment by siml142857** [comment]
> 将其他agent视为Soft obstacle是指sipps允许生成和其他agent相撞的node，也就是说可以plan有碰撞的path，但是sipps的第一优化目标也被更改为了最小化path上的碰撞的数量。 将其他agent视为Hard obstacle是指不允许生成和其他agent相撞的node， 只plan 无碰撞的path，优化目标也只是path 长度。

明白了，谢谢解答

**Comment by YangSVM** [comment]
请问hard和soft怎么选择和变化呢？在文章中似乎所有的智能体都设置成soft了。从文章中的“ Each time, it calls a single-
agent pathfinding algorithm (see Section 4) to find a path for an agent that minimizes the number of collisions with the new paths of the higher-priority agents in A s and the paths in P\P−. ” 这一段叙述中，似乎印证了所有都是soft。后面也只是提到了邻域的选择，没有提及将哪些设置为硬agent，哪些为软agent

**Comment by Jiaoyang-Li** [comment]
For MAPF-LNS2, we do not have any hard obstacles. Hard obstacles are used in EECBS*, which represents the constraints added by the high level.

**Comment by YangSVM** [comment]
Thanks a lot :-)
